/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accountsSol from "./Accounts.sol";
export type { accountsSol };
import type * as modulesSol from "./Modules.sol";
export type { modulesSol };
