/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Relayer,
  RelayerInterface,
} from "../../../contracts/Relayer.sol/Relayer";

const _abi = [
  {
    inputs: [],
    name: "spokePool",
    outputs: [
      {
        internalType: "contract SpokePoolInterface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "testBridge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Relayer__factory {
  static readonly abi = _abi;
  static createInterface(): RelayerInterface {
    return new Interface(_abi) as RelayerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Relayer {
    return new Contract(address, _abi, runner) as unknown as Relayer;
  }
}
