/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  V3SpokePoolInterface,
  V3SpokePoolInterfaceInterface,
} from "../../../contracts/Relayer.sol/V3SpokePoolInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "depositor",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "inputToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "outputToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "inputAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "destinationChainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "exclusiveRelayer",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "quoteTimestamp",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "fillDeadline",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "exclusivityDeadline",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "depositV3",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class V3SpokePoolInterface__factory {
  static readonly abi = _abi;
  static createInterface(): V3SpokePoolInterfaceInterface {
    return new Interface(_abi) as V3SpokePoolInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): V3SpokePoolInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as V3SpokePoolInterface;
  }
}
