/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AcrossSender,
  AcrossSenderInterface,
} from "../../../contracts/bridge/AcrossSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "uint96",
        name: "destinationChainId",
        type: "uint96",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendAcrossTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "spokePool",
    outputs: [
      {
        internalType: "contract V3SpokePoolInterface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AcrossSender__factory {
  static readonly abi = _abi;
  static createInterface(): AcrossSenderInterface {
    return new Interface(_abi) as AcrossSenderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AcrossSender {
    return new Contract(address, _abi, runner) as unknown as AcrossSender;
  }
}
