/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAcrossMessageHandlerInterface extends Interface {
  getFunction(
    nameOrSignature: "handleAcrossMessage" | "handleV3AcrossMessage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "handleAcrossMessage",
    values: [AddressLike, BigNumberish, boolean, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleV3AcrossMessage",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "handleAcrossMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleV3AcrossMessage",
    data: BytesLike
  ): Result;
}

export interface IAcrossMessageHandler extends BaseContract {
  connect(runner?: ContractRunner | null): IAcrossMessageHandler;
  waitForDeployment(): Promise<this>;

  interface: IAcrossMessageHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  handleAcrossMessage: TypedContractMethod<
    [
      tokenSent: AddressLike,
      amount: BigNumberish,
      fillCompleted: boolean,
      relayer: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  handleV3AcrossMessage: TypedContractMethod<
    [
      tokenSent: AddressLike,
      amount: BigNumberish,
      relayer: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "handleAcrossMessage"
  ): TypedContractMethod<
    [
      tokenSent: AddressLike,
      amount: BigNumberish,
      fillCompleted: boolean,
      relayer: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleV3AcrossMessage"
  ): TypedContractMethod<
    [
      tokenSent: AddressLike,
      amount: BigNumberish,
      relayer: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
