/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errorsSol from "./Errors.sol";
export type { errorsSol };
export type { IAcrossMessageHandler } from "./IAcrossMessageHandler";
export type { IFallbackRegister } from "./IFallbackRegister";
export type { IOwnerManager } from "./IOwnerManager";
export type { ISafe } from "./ISafe";
