/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SpokePoolInterface } from "./SpokePoolInterface";
export type { V3SpokePoolInterface } from "./V3SpokePoolInterface";
