/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TokenFallback {
  export type FallbackDataStruct = {
    target: AddressLike;
    selector: BytesLike;
    tokenAddressIndex: BigNumberish;
    amountIndex: BigNumberish;
    vaultAddressIndex: BigNumberish;
    data: BytesLike;
  };

  export type FallbackDataStructOutput = [
    target: string,
    selector: string,
    tokenAddressIndex: bigint,
    amountIndex: bigint,
    vaultAddressIndex: bigint,
    data: string
  ] & {
    target: string;
    selector: string;
    tokenAddressIndex: bigint;
    amountIndex: bigint;
    vaultAddressIndex: bigint;
    data: string;
  };
}

export interface BaseModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridgeFallbacks"
      | "getFallback"
      | "metadataHash"
      | "metadataProvider"
      | "name"
      | "removeTokenFallback"
      | "requiresPermissions"
      | "requiresRootAccess"
      | "sendAcrossTransaction"
      | "setTokenFallback"
      | "spokePool"
      | "supportsInterface"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Metadata"
      | "TokenFallbackAdded"
      | "TokenFallbackRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bridgeFallbacks",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFallback",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "metadataHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "metadataProvider",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeTokenFallback",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiresPermissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiresRootAccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendAcrossTransaction",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenFallback",
    values: [AddressLike, TokenFallback.FallbackDataStruct]
  ): string;
  encodeFunctionData(functionFragment: "spokePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "bridgeFallbacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metadataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metadataProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenFallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiresPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiresRootAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendAcrossTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenFallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spokePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace MetadataEvent {
  export type InputTuple = [metadataHash: BytesLike, data: BytesLike];
  export type OutputTuple = [metadataHash: string, data: string];
  export interface OutputObject {
    metadataHash: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFallbackAddedEvent {
  export type InputTuple = [
    safe: AddressLike,
    token: AddressLike,
    fallbackData: TokenFallback.FallbackDataStruct
  ];
  export type OutputTuple = [
    safe: string,
    token: string,
    fallbackData: TokenFallback.FallbackDataStructOutput
  ];
  export interface OutputObject {
    safe: string;
    token: string;
    fallbackData: TokenFallback.FallbackDataStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFallbackRemovedEvent {
  export type InputTuple = [safe: AddressLike, token: AddressLike];
  export type OutputTuple = [safe: string, token: string];
  export interface OutputObject {
    safe: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BaseModule extends BaseContract {
  connect(runner?: ContractRunner | null): BaseModule;
  waitForDeployment(): Promise<this>;

  interface: BaseModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeFallbacks: TypedContractMethod<
    [safe: AddressLike, token: AddressLike],
    [
      [string, string, bigint, bigint, bigint, string] & {
        target: string;
        selector: string;
        tokenAddressIndex: bigint;
        amountIndex: bigint;
        vaultAddressIndex: bigint;
        data: string;
      }
    ],
    "view"
  >;

  getFallback: TypedContractMethod<
    [safe: AddressLike, token: AddressLike],
    [
      [boolean, TokenFallback.FallbackDataStructOutput] & {
        exists: boolean;
        fallbackData: TokenFallback.FallbackDataStructOutput;
      }
    ],
    "view"
  >;

  metadataHash: TypedContractMethod<[], [string], "view">;

  metadataProvider: TypedContractMethod<
    [],
    [[bigint, string] & { providerType: bigint; location: string }],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  removeTokenFallback: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  requiresPermissions: TypedContractMethod<[], [bigint], "view">;

  requiresRootAccess: TypedContractMethod<[], [boolean], "view">;

  sendAcrossTransaction: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      destinationChainId: BigNumberish,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setTokenFallback: TypedContractMethod<
    [token: AddressLike, fallbackData: TokenFallback.FallbackDataStruct],
    [void],
    "nonpayable"
  >;

  spokePool: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeFallbacks"
  ): TypedContractMethod<
    [safe: AddressLike, token: AddressLike],
    [
      [string, string, bigint, bigint, bigint, string] & {
        target: string;
        selector: string;
        tokenAddressIndex: bigint;
        amountIndex: bigint;
        vaultAddressIndex: bigint;
        data: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFallback"
  ): TypedContractMethod<
    [safe: AddressLike, token: AddressLike],
    [
      [boolean, TokenFallback.FallbackDataStructOutput] & {
        exists: boolean;
        fallbackData: TokenFallback.FallbackDataStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "metadataHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "metadataProvider"
  ): TypedContractMethod<
    [],
    [[bigint, string] & { providerType: bigint; location: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeTokenFallback"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiresPermissions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requiresRootAccess"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "sendAcrossTransaction"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      destinationChainId: BigNumberish,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenFallback"
  ): TypedContractMethod<
    [token: AddressLike, fallbackData: TokenFallback.FallbackDataStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spokePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Metadata"
  ): TypedContractEvent<
    MetadataEvent.InputTuple,
    MetadataEvent.OutputTuple,
    MetadataEvent.OutputObject
  >;
  getEvent(
    key: "TokenFallbackAdded"
  ): TypedContractEvent<
    TokenFallbackAddedEvent.InputTuple,
    TokenFallbackAddedEvent.OutputTuple,
    TokenFallbackAddedEvent.OutputObject
  >;
  getEvent(
    key: "TokenFallbackRemoved"
  ): TypedContractEvent<
    TokenFallbackRemovedEvent.InputTuple,
    TokenFallbackRemovedEvent.OutputTuple,
    TokenFallbackRemovedEvent.OutputObject
  >;

  filters: {
    "Metadata(bytes32,bytes)": TypedContractEvent<
      MetadataEvent.InputTuple,
      MetadataEvent.OutputTuple,
      MetadataEvent.OutputObject
    >;
    Metadata: TypedContractEvent<
      MetadataEvent.InputTuple,
      MetadataEvent.OutputTuple,
      MetadataEvent.OutputObject
    >;

    "TokenFallbackAdded(address,address,tuple)": TypedContractEvent<
      TokenFallbackAddedEvent.InputTuple,
      TokenFallbackAddedEvent.OutputTuple,
      TokenFallbackAddedEvent.OutputObject
    >;
    TokenFallbackAdded: TypedContractEvent<
      TokenFallbackAddedEvent.InputTuple,
      TokenFallbackAddedEvent.OutputTuple,
      TokenFallbackAddedEvent.OutputObject
    >;

    "TokenFallbackRemoved(address,address)": TypedContractEvent<
      TokenFallbackRemovedEvent.InputTuple,
      TokenFallbackRemovedEvent.OutputTuple,
      TokenFallbackRemovedEvent.OutputObject
    >;
    TokenFallbackRemoved: TypedContractEvent<
      TokenFallbackRemovedEvent.InputTuple,
      TokenFallbackRemovedEvent.OutputTuple,
      TokenFallbackRemovedEvent.OutputObject
    >;
  };
}
