/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baseSol from "./Base.sol";
export type { baseSol };
export type { BaseModule } from "./BaseModule";
export type { BridgeFallbackHandler } from "./BridgeFallbackHandler";
