/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface BasePluginWithEventMetadataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "metadataHash"
      | "metadataProvider"
      | "name"
      | "requiresPermissions"
      | "requiresRootAccess"
      | "supportsInterface"
      | "version"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Metadata"): EventFragment;

  encodeFunctionData(
    functionFragment: "metadataHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "metadataProvider",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requiresPermissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiresRootAccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "metadataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metadataProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requiresPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiresRootAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace MetadataEvent {
  export type InputTuple = [metadataHash: BytesLike, data: BytesLike];
  export type OutputTuple = [metadataHash: string, data: string];
  export interface OutputObject {
    metadataHash: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BasePluginWithEventMetadata extends BaseContract {
  connect(runner?: ContractRunner | null): BasePluginWithEventMetadata;
  waitForDeployment(): Promise<this>;

  interface: BasePluginWithEventMetadataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  metadataHash: TypedContractMethod<[], [string], "view">;

  metadataProvider: TypedContractMethod<
    [],
    [[bigint, string] & { providerType: bigint; location: string }],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  requiresPermissions: TypedContractMethod<[], [bigint], "view">;

  requiresRootAccess: TypedContractMethod<[], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "metadataHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "metadataProvider"
  ): TypedContractMethod<
    [],
    [[bigint, string] & { providerType: bigint; location: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requiresPermissions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requiresRootAccess"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Metadata"
  ): TypedContractEvent<
    MetadataEvent.InputTuple,
    MetadataEvent.OutputTuple,
    MetadataEvent.OutputObject
  >;

  filters: {
    "Metadata(bytes32,bytes)": TypedContractEvent<
      MetadataEvent.InputTuple,
      MetadataEvent.OutputTuple,
      MetadataEvent.OutputObject
    >;
    Metadata: TypedContractEvent<
      MetadataEvent.InputTuple,
      MetadataEvent.OutputTuple,
      MetadataEvent.OutputObject
    >;
  };
}
