/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasePlugin } from "./BasePlugin";
export type { BasePluginWithEventMetadata } from "./BasePluginWithEventMetadata";
export type { BasePluginWithStoredMetadata } from "./BasePluginWithStoredMetadata";
export type { IMetadataProvider } from "./IMetadataProvider";
