/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAcrossMessageHandler,
  IAcrossMessageHandlerInterface,
} from "../../../contracts/interfaces/IAcrossMessageHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenSent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "fillCompleted",
        type: "bool",
      },
      {
        internalType: "address",
        name: "relayer",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "handleAcrossMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenSent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "relayer",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "handleV3AcrossMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAcrossMessageHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IAcrossMessageHandlerInterface {
    return new Interface(_abi) as IAcrossMessageHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAcrossMessageHandler {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAcrossMessageHandler;
  }
}
