/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AccountEntry,
  AccountEntryInterface,
} from "../../../contracts/safe/AccountEntry";

const _abi = [
  {
    inputs: [],
    name: "InvalidEntryPoint",
    type: "error",
  },
  {
    inputs: [],
    name: "SUPPORTED_ENTRYPOINT",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AccountEntry__factory {
  static readonly abi = _abi;
  static createInterface(): AccountEntryInterface {
    return new Interface(_abi) as AccountEntryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccountEntry {
    return new Contract(address, _abi, runner) as unknown as AccountEntry;
  }
}
