[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/forge"
cache_path = "cache_forge"
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
# match_path = "*.t.sol"
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "@openzeppelin/contracts-v5/=node_modules/@openzeppelin/contracts-v5/",
    "@jasmine-energy/pools-contracts/=node_modules/@jasmine-energy/pools-contracts/",
    "contracts/=contracts/",
    "forge-std/=lib/forge-std/src",
    "ds-test/=node_modules/ds-test/src",
]

[etherscan]
mumbai = { key = "${ETHERSCAN_API_KEY}", chain = "mumbai", url = "https://api-testnet.polygonscan.com/" }
polygon = { key = "${ETHERSCAN_API_KEY}", chain = "polygon", url = "https://api.polygonscan.com/" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
