/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISafeProtocolFunctionHandler } from "./ISafeProtocolFunctionHandler";
export type { ISafeProtocolHooks } from "./ISafeProtocolHooks";
export type { ISafeProtocolPlugin } from "./ISafeProtocolPlugin";
export type { ISafeProtocolStaticFunctionHandler } from "./ISafeProtocolStaticFunctionHandler";
